packages:
  - 'packages/*'

catalog:
  '@aztec/aztec.js': '4.2.0-aztecnr-rc.2'
  '@aztec/accounts': '4.2.0-aztecnr-rc.2'
  '@aztec/constants': '4.2.0-aztecnr-rc.2'
  '@aztec/entrypoints': '4.2.0-aztecnr-rc.2'
  '@aztec/ethereum': '4.2.0-aztecnr-rc.2'
  '@aztec/foundation': '4.2.0-aztecnr-rc.2'
  '@aztec/noir-contracts.js': '4.2.0-aztecnr-rc.2'
  '@aztec/pxe': '4.2.0-aztecnr-rc.2'
  '@aztec/stdlib': '4.2.0-aztecnr-rc.2'
  '@aztec/wallets': '4.2.0-aztecnr-rc.2'
  '@aztec/wallet-sdk': '4.2.0-aztecnr-rc.2'
  '@aztec/protocol-contracts': '4.2.0-aztecnr-rc.2'
  '@jest/globals': '^30.0.5'
  '@types/jest': '^30.0.0'
  tsx: '^4.0.0'
  dotenv: '^17.2.1'
  jest: '^30.0.5'
  typescript: '^5.0.0'
